[build]
  publish = "frontend"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[cron]]
  schedule = "*/5 * * * *"
  name = "heartbeat"
  function = "heartbeat"